module.exports = {
	prefix: '',
	important: false,
	separator: ':',
	theme: {
		gridColumns : {
			'1/2': '50%',
			'1/3': '33.33333%',
			'2/3': '66.66667%',
			'2/5': '20%',
			'1/4': '25%',
			'3/4': '75%',
			'1/5': '20%',
			'2/5': '40%',
			'3/5': '60%',
			'4/5': '80%',
			'1/6': '16.66667%',
			'5/6': '83.33333%',
			'1/12' : '8.333333333%',
			'2/12' : '16.66666667%',
			'3/12' : '25%',
			'4/12' : '33.33333333%',
			'5/12' : '41.66666667%',
			'6/12' : '50%',
			'7/12' : '58.33333333%',
			'8/12' : '66.66666667%',
			'9/12' : '75%',
			'10/12' : '83.33333333%',
			'11/12' : '91.66666667%',	
		},
		colors: {
			transparent: 'transparent',
			black: '#000',
			white: '#fff',
			gray: {
				000: '#f9f9f9',
				100: '#111',
				200: '#222',
				300: '#333',
				400: '#ccc',
				600: '#666',
				900: '#999',
			},
			'entry-type-pages': '#000',
		},
		spacing: {
			px: '1px',
			'0': '0',
			'5px': '5px',
			'10px': '10px',
			'15px': '15px',
			'20px': '20px',
			'25px': '25px',
			'30px': '30px',
			'35px': '35px',
			'40px': '40px',
			'45px': '45px',
			'50px': '50px',
			'55px': '55px',
			'60px': '60px',
			'65px': '65px',
			'70px': '70px',
			'75px': '75px',
			'80px': '80px',
			'85px': '85px',
			'90px': '90px',
			'95px': '95px',
			'100px': '100px',
		},
		screens: {
			sm: '576px',
			md: '768px',
			lg: '992px',
			xl: '1440px',
		},
		fontFamily: {
			roboto: [
				'Roboto',
				'"Helvetica Neue"',
				'Arial',
			],
			georgia: [
				'Georgia',
				'Cambria',
				'"Times New Roman"',
				'Times',
				'serif',
			],
		},
		fontSize: {
			t1: '5.75rem',
			t2: '4.875rem',
			t3: '3rem',
			t4: '2.125rem',
			t5: '1.25rem',
		},
		fontWeight: {
			hairline: 100,
			thin: 200,
			light: 300,
			normal: 400,
			medium: 500,
			semibold: 600,
			bold: 700,
			extrabold: 800,
			black: 900,
		},
		lineHeight: {
			none: 1,
			tight: 1.25,
			snug: 1.375,
			normal: 1.5,
			relaxed: 1.625,
			loose: 2,
		},
		letterSpacing: {
			tighter: '-.05em',
			tight: '-.025em',
			normal: '0',
			wide: '.025em',
			wider: '.05em',
			widest: '.1em',
		},
		textColor: theme => theme('colors'),
		backgroundColor: theme => theme('colors'),
		backgroundPosition: {
			bottom: 'bottom',
			center: 'center',
			left: 'left',
			'left-bottom': 'left bottom',
			'left-top': 'left top',
			right: 'right',
			'right-bottom': 'right bottom',
			'right-top': 'right top',
			top: 'top',
		},
		backgroundSize: {
			auto: 'auto',
			cover: 'cover',
			contain: 'contain',
		},
		borderWidth: {
			default: '1px',
			'0': '0',
			'2': '2px',
			'4': '4px',
			'8': '8px',
		},
		borderColor: theme => {
			return global.Object.assign(
				{
					default: theme('colors.gray.300', 'currentColor'),
				},
				theme('colors'),
			);
		},
		borderRadius: {
			none: '0',
			default: '10px',
		},
		cursor: {
			auto: 'auto',
			default: 'default',
			pointer: 'pointer',
			wait: 'wait',
			move: 'move',
			'not-allowed': 'not-allowed',
		},
		width: theme => ({
			auto: 'auto',
			...theme('spacing'),
			...theme('gridColumns'),
			full: '100%',
			screen: '100vw',
		}),
		height: theme => ({
			auto: 'auto',
			...theme('spacing'),
			full: '100%',
			screen: '100vh',
		}),
		minWidth: {
			'0': '0',
			full: '100%',
		},
		minHeight: {
			'0': '0',
			full: '100%',
			screen: '100vh',
		},
		maxWidth: {
			xs: '20rem',
			sm: '24rem',
			md: '28rem',
			lg: '32rem',
			xl: '36rem',
			'2xl': '42rem',
			'3xl': '48rem',
			'4xl': '56rem',
			'5xl': '64rem',
			'6xl': '72rem',
			full: '100%',
			website: '1240px'
		},
		maxHeight: {
			full: '100%',
			screen: '100vh',
		},
		padding: theme => ({
			xs: '10px',
			sm: '15px',
			md: '20px',
			lg: '25px',
			xl: '25px',
			...theme('spacing'),
		}),
		margin: (theme, { negative }) => ({
			auto: 'auto',
			...theme('spacing'),
			...negative(theme('spacing')),
		}),
		negativeMargin: theme => theme('spacing'),
		objectPosition: {
			bottom: 'bottom',
			center: 'center',
			left: 'left',
			'left-bottom': 'left bottom',
			'left-top': 'left top',
			right: 'right',
			'right-bottom': 'right bottom',
			'right-top': 'right top',
			top: 'top',
		},
		boxShadow: {
			default:
				'0 1px 3px 0 rgba(0, 0, 0, .1), 0 1px 2px 0 rgba(0, 0, 0, .06)',
			md:
				'0 4px 6px -1px rgba(0, 0, 0, .1), 0 2px 4px -1px rgba(0, 0, 0, .06)',
			lg:
				'0 10px 15px -3px rgba(0, 0, 0, .1), 0 4px 6px -2px rgba(0, 0, 0, .05)',
			xl:
				'0 20px 25px -5px rgba(0, 0, 0, .1), 0 10px 10px -5px rgba(0, 0, 0, .04)',
			'2xl': '0 25px 50px -12px rgba(0, 0, 0, .25)',
			inner: 'inset 0 2px 4px 0 rgba(0,0,0,0.06)',
			outline: '0 0 0 3px rgba(66,153,225,0.5)',
			none: 'none',
		},
		zIndex: {
			auto: 'auto',
			'0': 0,
			'10': 10,
			'20': 20,
			'30': 30,
			'40': 40,
			'50': 50,
			'nav-sticky': '99',
			'nav-mobile': '99',
			'overlay': '99',
			'modal': '100',
			'debug-bp': '10000',
		},
		opacity: {
			'0': '0',
			'25': '.25',
			'50': '.5',
			'75': '.75',
			'100': '1',
		},
		fill: {
			current: 'currentColor',
		},
		stroke: {
			current: 'currentColor',
		},
		flex: {
			'1': '1 1 0%',
			auto: '1 1 auto',
			initial: '0 1 auto',
			none: 'none',
		},
		flexGrow: {
			'0': 0,
			default: 1,
		},
		flexShrink: {
			'0': 0,
			default: 1,
		},
		listStyleType: {
			none: 'none',
			disc: 'disc',
			decimal: 'decimal',
		},
		inset: {
			'0': 0,
			auto: 'auto',
		},
		container: {
			center: true,
			padding: '1rem',
		},
		iconSize: {
			auto: 'auto',
			'0': 0,
			'10': 10,
			'20': 20,
			'30': 30,
			'40': 40,
			'50': 50,
		},
	},
	variants: {
		appearance: ['responsive'],
		backgroundAttachment: ['responsive'],
		backgroundColor: ['responsive', 'hover', 'focus'],
		backgroundPosition: ['responsive'],
		backgroundRepeat: ['responsive'],
		backgroundSize: ['responsive'],
		borderCollapse: [],
		borderColor: ['responsive', 'hover', 'focus'],
		borderRadius: ['responsive'],
		borderStyle: ['responsive'],
		borderWidth: ['responsive'],
		cursor: ['responsive'],
		display: ['responsive'],
		flexDirection: ['responsive'],
		flexWrap: ['responsive'],
		alignItems: ['responsive'],
		alignSelf: ['responsive'],
		justifyContent: ['responsive'],
		alignContent: ['responsive'],
		flex: ['responsive'],
		flexGrow: ['responsive'],
		flexShrink: ['responsive'],
		float: ['responsive'],
		fontFamily: ['responsive'],
		fontWeight: ['responsive', 'hover', 'focus'],
		height: ['responsive'],
		lineHeight: ['responsive'],
		listStylePosition: ['responsive'],
		listStyleType: ['responsive'],
		margin: ['responsive'],
		maxHeight: ['responsive'],
		maxWidth: ['responsive'],
		minHeight: ['responsive'],
		minWidth: ['responsive'],
		negativeMargin: ['responsive'],
		objectFit: ['responsive'],
		objectPosition: ['responsive'],
		opacity: ['responsive'],
		outline: ['focus'],
		overflow: ['responsive'],
		padding: ['responsive'],
		pointerEvents: ['responsive'],
		position: ['responsive'],
		inset: ['responsive'],
		resize: ['responsive'],
		boxShadow: ['responsive', 'hover', 'focus'],
		fill: [],
		stroke: [],
		tableLayout: ['responsive'],
		textAlign: ['responsive'],
		textColor: ['responsive', 'hover', 'focus'],
		fontSize: ['responsive'],
		fontStyle: ['responsive'],
		textTransform: ['responsive'],
		textDecoration: ['responsive', 'hover', 'focus'],
		fontSmoothing: ['responsive'],
		letterSpacing: ['responsive'],
		userSelect: ['responsive'],
		verticalAlign: ['responsive'],
		visibility: ['responsive'],
		whitespace: ['responsive'],
		wordBreak: ['responsive'],
		width: ['responsive'],
		zIndex: ['responsive'],
		iconSize: ['responsive'],
	},
	corePlugins: {
		
	},
	plugins: [
		require('./tailwindcss/plugins/icon-size')(['responsive']),
		require('./tailwindcss/plugins/transition')(['responsive']),
	],
};
